# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b6d52c6bde35d6dfddde8dc6cb7bf6cb606d328c316805d61a93658383ce81db7db7ac505ebaf1ec09001b6dbc8ed8e67f0dbe1c020d43a80454f26476da92b

test:
  secret_key_base: e17b6d62042471fc7629743316ab6c4d9352f05a80bd9b230071da97b7f9a5ddd895f70d7853b885a4d057390f218fada12131c7b585491bdd5fdc80eedce267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
